@baseUrl = http://localhost:4000/api/pl8s
@id = 60a8e493018286dd93cb188a

GET {{baseUrl}}

###

GET {{baseUrl}}/{{id}}

###
POST http://localhost:4000/api/become-a-m8
content-type: application/json

{
  "username": "newUser",
  "email": "newUser@email",
  "avatar": "this is an image string",
  "password": "password",
  "passwordConfirmation": "password",
  "m8s": [],
  "highScore": 0,
  "r8dPl8s": []
}

###

GET {{baseUrl}}/search?description=meaty

###

POST {{baseUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtOElkIjoiNjBhOGU5NTkxZjhhYjNkZGI1OWU5NDI2IiwiaWF0IjoxNjIxNjg1NDI0LCJleHAiOjE2MjE3Mjg2MjR9._AbQ4t7KDuaNvi8gK6NBbUfmR-kIZBsp0wU67XN6n7I
content-type: application/json

{
  "name": "test",
  "origin": "test",
  "description": "test",
  "image": "test",
  "ingredients": ["test"],
  "recipe": ["test"],
  "prepTime": 10,
  "cookTime": 10
}

###
POST http://localhost:4000/api/login
content-type: application/json

{
  "email": "dom@dom",
  "password": "dom"
}

