@baseUrl = http://localhost:4000/api/pl8s
@id = 60a7d097986e6b47fc639d9e

GET {{baseUrl}}

###

GET {{baseUrl}}/{{id}}

###

GET {{baseUrl}}/search?description=meaty

###

POST {{baseUrl}}

{
  "name": "test",
  "origin": "test",
  "description": "test",
  "image": "test",
  "ingredients": ["test"],
  "recipe": ["test"],
  "prepTime": 10,
  "cookTime": 10,
}